/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface UniversalDAOInterface extends utils.Interface {
  functions: {
    "createProposal(bytes32,string)": FunctionFragment;
    "daos(bytes32)": FunctionFragment;
    "initialize()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "registerDAO(bytes32,address,address,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setDaoToken(bytes32,address)": FunctionFragment;
    "setMember(bytes32,address,bool)": FunctionFragment;
    "setMinTokenHolding(bytes32,uint256)": FunctionFragment;
    "setPause(bool)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vote(bytes32,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createProposal"
      | "daos"
      | "initialize"
      | "owner"
      | "paused"
      | "registerDAO"
      | "renounceOwnership"
      | "setDaoToken"
      | "setMember"
      | "setMinTokenHolding"
      | "setPause"
      | "transferOwnership"
      | "vote"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createProposal",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "daos",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDAO",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDaoToken",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMember",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTokenHolding",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPause",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "daos", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDAO",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDaoToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinTokenHolding",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;

  events: {
    "DAORegistered(bytes32,address,address,uint256)": EventFragment;
    "DaoTokenSet(bytes32,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "MemberSet(bytes32,address,bool)": EventFragment;
    "MinTokenHoldingSet(bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "ProposalCreated(bytes32,uint256,string)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Voted(bytes32,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DAORegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DaoTokenSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MinTokenHoldingSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Voted"): EventFragment;
}

export interface DAORegisteredEventObject {
  daoId: string;
  admin: string;
  token: string;
  minTokenHolding: BigNumber;
}
export type DAORegisteredEvent = TypedEvent<
  [string, string, string, BigNumber],
  DAORegisteredEventObject
>;

export type DAORegisteredEventFilter = TypedEventFilter<DAORegisteredEvent>;

export interface DaoTokenSetEventObject {
  daoId: string;
  token: string;
}
export type DaoTokenSetEvent = TypedEvent<
  [string, string],
  DaoTokenSetEventObject
>;

export type DaoTokenSetEventFilter = TypedEventFilter<DaoTokenSetEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface MemberSetEventObject {
  daoId: string;
  member: string;
  setRole: boolean;
}
export type MemberSetEvent = TypedEvent<
  [string, string, boolean],
  MemberSetEventObject
>;

export type MemberSetEventFilter = TypedEventFilter<MemberSetEvent>;

export interface MinTokenHoldingSetEventObject {
  daoId: string;
  minTokenHolding: BigNumber;
}
export type MinTokenHoldingSetEvent = TypedEvent<
  [string, BigNumber],
  MinTokenHoldingSetEventObject
>;

export type MinTokenHoldingSetEventFilter =
  TypedEventFilter<MinTokenHoldingSetEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface ProposalCreatedEventObject {
  daoId: string;
  proposalId: BigNumber;
  description: string;
}
export type ProposalCreatedEvent = TypedEvent<
  [string, BigNumber, string],
  ProposalCreatedEventObject
>;

export type ProposalCreatedEventFilter = TypedEventFilter<ProposalCreatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface VotedEventObject {
  daoId: string;
  proposalId: BigNumber;
  voter: string;
}
export type VotedEvent = TypedEvent<
  [string, BigNumber, string],
  VotedEventObject
>;

export type VotedEventFilter = TypedEventFilter<VotedEvent>;

export interface UniversalDAO extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UniversalDAOInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createProposal(
      _daoId: PromiseOrValue<BytesLike>,
      _description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    daos(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        admin: string;
        token: string;
        minTokenHolding: BigNumber;
        proposalCount: BigNumber;
      }
    >;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    registerDAO(
      _daoId: PromiseOrValue<BytesLike>,
      _admin: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDaoToken(
      _daoId: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMember(
      _daoId: PromiseOrValue<BytesLike>,
      _member: PromiseOrValue<string>,
      _setRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinTokenHolding(
      _daoId: PromiseOrValue<BytesLike>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPause(
      _setPause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vote(
      _daoId: PromiseOrValue<BytesLike>,
      _proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createProposal(
    _daoId: PromiseOrValue<BytesLike>,
    _description: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  daos(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, BigNumber] & {
      admin: string;
      token: string;
      minTokenHolding: BigNumber;
      proposalCount: BigNumber;
    }
  >;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  registerDAO(
    _daoId: PromiseOrValue<BytesLike>,
    _admin: PromiseOrValue<string>,
    _token: PromiseOrValue<string>,
    _minTokenHolding: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDaoToken(
    _daoId: PromiseOrValue<BytesLike>,
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMember(
    _daoId: PromiseOrValue<BytesLike>,
    _member: PromiseOrValue<string>,
    _setRole: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinTokenHolding(
    _daoId: PromiseOrValue<BytesLike>,
    _minTokenHolding: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPause(
    _setPause: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vote(
    _daoId: PromiseOrValue<BytesLike>,
    _proposalId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createProposal(
      _daoId: PromiseOrValue<BytesLike>,
      _description: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    daos(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, BigNumber] & {
        admin: string;
        token: string;
        minTokenHolding: BigNumber;
        proposalCount: BigNumber;
      }
    >;

    initialize(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    registerDAO(
      _daoId: PromiseOrValue<BytesLike>,
      _admin: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setDaoToken(
      _daoId: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMember(
      _daoId: PromiseOrValue<BytesLike>,
      _member: PromiseOrValue<string>,
      _setRole: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinTokenHolding(
      _daoId: PromiseOrValue<BytesLike>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPause(
      _setPause: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vote(
      _daoId: PromiseOrValue<BytesLike>,
      _proposalId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DAORegistered(bytes32,address,address,uint256)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      admin?: PromiseOrValue<string> | null,
      token?: null,
      minTokenHolding?: null
    ): DAORegisteredEventFilter;
    DAORegistered(
      daoId?: PromiseOrValue<BytesLike> | null,
      admin?: PromiseOrValue<string> | null,
      token?: null,
      minTokenHolding?: null
    ): DAORegisteredEventFilter;

    "DaoTokenSet(bytes32,address)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      token?: null
    ): DaoTokenSetEventFilter;
    DaoTokenSet(
      daoId?: PromiseOrValue<BytesLike> | null,
      token?: null
    ): DaoTokenSetEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "MemberSet(bytes32,address,bool)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      member?: PromiseOrValue<string> | null,
      setRole?: null
    ): MemberSetEventFilter;
    MemberSet(
      daoId?: PromiseOrValue<BytesLike> | null,
      member?: PromiseOrValue<string> | null,
      setRole?: null
    ): MemberSetEventFilter;

    "MinTokenHoldingSet(bytes32,uint256)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      minTokenHolding?: null
    ): MinTokenHoldingSetEventFilter;
    MinTokenHoldingSet(
      daoId?: PromiseOrValue<BytesLike> | null,
      minTokenHolding?: null
    ): MinTokenHoldingSetEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "ProposalCreated(bytes32,uint256,string)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      proposalId?: null,
      description?: null
    ): ProposalCreatedEventFilter;
    ProposalCreated(
      daoId?: PromiseOrValue<BytesLike> | null,
      proposalId?: null,
      description?: null
    ): ProposalCreatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Voted(bytes32,uint256,address)"(
      daoId?: PromiseOrValue<BytesLike> | null,
      proposalId?: null,
      voter?: PromiseOrValue<string> | null
    ): VotedEventFilter;
    Voted(
      daoId?: PromiseOrValue<BytesLike> | null,
      proposalId?: null,
      voter?: PromiseOrValue<string> | null
    ): VotedEventFilter;
  };

  estimateGas: {
    createProposal(
      _daoId: PromiseOrValue<BytesLike>,
      _description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    daos(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    registerDAO(
      _daoId: PromiseOrValue<BytesLike>,
      _admin: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDaoToken(
      _daoId: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMember(
      _daoId: PromiseOrValue<BytesLike>,
      _member: PromiseOrValue<string>,
      _setRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinTokenHolding(
      _daoId: PromiseOrValue<BytesLike>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPause(
      _setPause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vote(
      _daoId: PromiseOrValue<BytesLike>,
      _proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createProposal(
      _daoId: PromiseOrValue<BytesLike>,
      _description: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    daos(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerDAO(
      _daoId: PromiseOrValue<BytesLike>,
      _admin: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDaoToken(
      _daoId: PromiseOrValue<BytesLike>,
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMember(
      _daoId: PromiseOrValue<BytesLike>,
      _member: PromiseOrValue<string>,
      _setRole: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinTokenHolding(
      _daoId: PromiseOrValue<BytesLike>,
      _minTokenHolding: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPause(
      _setPause: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vote(
      _daoId: PromiseOrValue<BytesLike>,
      _proposalId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
